### ISSUE TITLE
base-prelude violates the PVP

### ISSUE THREAD

**Issue by hvr** [nikita-volkov/base-prelude#13]
I appears as if `BasePrelude` violates the PVP contract by advertising a version `1.0.1` and yet exposing a greatly fluctuating API (and not even placing a sensible upper bound on `base` anymore to contain the risk).

I'd like to remind that https://hackage.haskell.org/ states that "All packages should follow the Package Versioning Policy (PVP)." and `base-prelude` does not state in its description that it deviates from the PVP contract.

I'm worried because packages on Hackage are starting to make use of `base-prelude` and without proper guidance that will cause more busywork for Hackage Trustees to keep install-plans from bitrotting due to inaccurate version-bounds.

**Comment by nikita-volkov** [comment]
> BasePrelude violates the PVP contract by advertising a version 1.0.1 and yet exposing a greatly fluctuating API (and not even placing a sensible upper bound on base anymore to contain the risk).

By violation of PVP do you imply the `base < 5` bound? If so, could you clarify in which way it violates the contract? Are there any other things causing the violation of the contract?

I definitely do not want to violate PVP, so I'm asking this with the only intent of resolving the issue.

**Comment by hvr** [comment]
The `base < 5` part per se does not constitute a violation currently. Whether it does will only become clear when e.g. base-4.9.1 is released.

I'm mostly referring to `BasePrelude`'s exports fluctuating even though the `base-prelude` package version stays fixed. I.e. if you depend on `base-prelude == 1.0.1.*` and `import BasePrelude` unqualified, you already now get a different set of imports based on the GHC version. So `base-prelude` clearly violates the PVP purpose, namely to allow for lower/upper-bounds to determine the exposed API.

**Comment by nikita-volkov** [comment]
I see and agree. This then means that the package has been violating PVP starting from its first release and its not something that only appeared with the latest release of the package.

I see three ways of resolving this:

1. Update the package docs to include the notion of deviation from PVP.

2. Have individual versions of the package per each major version of "base".

3. Make all reexports explicit.

The last two options sound very tough from the maintenance perspective, so I'm leaning towards the first option. What's your take on it or suggestions?

**Comment by hvr** [comment]
At this point (since as you correctly asserted, this has been ongoing), I agree that 1. is probably the best compromise. Since `base-prelude` is a shim on `base`, the recommendation I would give is to set accurate (transitive) bounds on `base`, preferably by testing compatibility empirically via Travis or other means. It still makes sense to set (lower) version bounds on `base-prelude` as well, as `base-prelude` may add new compat-definitions to the ones it already adds now.

**Comment by nikita-volkov** [comment]
I agree.

**Comment by nikita-volkov** [comment]
> It still makes sense to set version bounds on base-prelude as well, as base-prelude may add new compat-definitions to the ones it already adds now.

In that case I'll just bump the major version.

**Comment by nikita-volkov** [comment]
Okay the latest release includes a notion of the versioning policy.
