### ISSUE TITLE
Reexport (&) and so on when we can

### ISSUE THREAD

**Issue by neongreen** [nikita-volkov/base-prelude#14]

**Comment by neongreen** [comment]
Since currently `&` is always reimplemented, it conflicts with other reexports of `&`. For instance, even if you don't care about compatibility with base-4.6, you still have to do

``` haskell
import BasePrelude
import Lens.Micro.Platform hiding ((&))
```

instead of

``` haskell
import BasePrelude
import Lens.Micro.Platform
```

(because `Lens.Micro` reexports `&` from `Data.Function` when it can).

**Comment by nikita-volkov** [comment]
Can. Be fixed with CPP. Can you make a PR?

**Comment by neongreen** [comment]
Yep, sure.
