### ISSUE TITLE
Fails to compile with GHC 7.4.2

### ISSUE THREAD

**Issue by hvr** [nikita-volkov/base-prelude#4]
No single version of `base-prelude` compiles with GHC 7.4.2, and yet the cabal file accepts `base-4.5`.

See https://ghc.haskell.org/~hvr/buildreports/base-prelude.html for details (look at the HTML source if the mouse-over text popups aren't readable). I've already edited all the `base-prelude` releases files on Hackage to have a tighter `base >= 4.6` constraint.

**Comment by nikita-volkov** [comment]
I originally only intended to provide support for GHC 7.6 and later, so it's a pretty much expected build failure. However for some reason up to this moment I was certain that "base-4.5" was shipped with GHC 7.6. I'll update the project accordingly.

Thank you.

**Comment by hvr** [comment]
btw, for future reference, in case you haven't seen it yet:

https://ghc.haskell.org/trac/ghc/wiki/Commentary/Libraries/VersionHistory

**Comment by nikita-volkov** [comment]
Fixed in 0.1.14, where support for GHC 7.10 is also provided.

Thanks
