### ISSUE TITLE
id and (.) are ambiguous

### ISSUE THREAD

**Issue by maxigit** [nikita-volkov/base-prelude#8]
I'm using GHC 7.10.3 I don't know if it's a regression  or not but they are already in the Prelude, so they need hidding.

**Comment by nikita-volkov** [comment]
BasePrelude is only supposed to be used in combination with the `NoImplicitPrelude` pragma.

**Comment by maxigit** [comment]
I didn't realize that. It's a shame because hiding a function has to be done only once (by one people) whereas the pragma as to be done over and over.

**Comment by nikita-volkov** [comment]
The project is not about doing something once, it's about replacing the standard Prelude with a more general one. You'd discover way more functions in BasePrelude, which would conflict with the standard Prelude, if you did the change you suggested.

BTW, FYI, pragmas can be done project-wide, so member-hiding is not an issue. E.g.: https://github.com/nikita-volkov/hasql/blob/81f78acf0d90913360ec2d991b246daed948ca81/hasql.cabal#L44-L45

**Comment by maxigit** [comment]
Fair enough, I just think it would be a "better" replacement if you could just do `import BasePrelude` and nothing else. You can indeed do pragmas project-wide, but you still have to do it for every project and every target. Anyway, that's your decision.

**Comment by nikita-volkov** [comment]
> I just think it would be a "better" replacement if you could just do import BasePrelude and nothing else.

It wouldn't be a replacement then, but an extension. Either way, you'd have to lose an important property of BasePrelude: the preference of polymorphic functions, which would conflict with their monomorphic counterparts from Prelude.

> You can indeed do pragmas project-wide, but you still have to do it for every project and every target.

And what's the problem about that?
