### ISSUE TITLE
No re-export of Data.Bifunctor

### ISSUE THREAD

**Issue by kozross** [nikita-volkov/base-prelude#9]
There don't appear to be any clashes, and this is a very useful thing to have available. Why not re-export it as well?

**Comment by nikita-volkov** [comment]
Sure! Care to make a PR? Just don't forget to add a CPP clause, because Bifunctor only appeared in "base" 4.8.

**Comment by kozross** [comment]
Sorry if this is a daft question, but what is a CPP clause?

**Comment by nikita-volkov** [comment]
A C-preprocessor instruction, which will check the version of a package. E.g., https://github.com/nikita-volkov/postgresql-binary/blob/d509feafb9e398aa07feac4b84ab07e8e9fc4327/library/PostgreSQL/Binary/Encoder.hs#L227-L233

**Comment by kozross** [comment]
Actually, there *is* a clash between Bifunctor and Arrow - both have functions named ```first``` and ```second```. Guess Bifunctor will have to stay separate, unless you have a strategy to avoid this.

**Comment by nikita-volkov** [comment]
Oh yeah, right. Well, arrows never got to catch the wind despite being there for years now. I think it's okay to give preference to Bifunctor. We'll just have to bump the major version of "base-prelude" then.
